[package]
name = "byint"
version = "0.1.0"
authors = ["Miroslav Kr√Ωsl <mkrysl@protonmail.com>"]
edition = "2018"
description = "Bytecode interpreter with simple graphical visualizer."

[dependencies]
